name: aruba-population-analysis
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - openpyxl
  - matplotlib
  - seaborn
  - sqlalchemy
  - statsmodels
  - scikit-learn
  - scipy
  - pyarrow
  - jupyter
  - ipykernel
  - pytest
  - pip
